In [1]:
import numpy as np
import pandas as pd

# Task 1

Создайте датафрейм из рандомно сгенеренного нампай массива целых чисел 10х10 и имен колонок:



```
col = ['col_1', 'col_2', 'col_3', ....]
```




In [2]:
col_names = ['col_' + str(i) for i in range(1, 11)]
col_names

['col_1',
 'col_2',
 'col_3',
 'col_4',
 'col_5',
 'col_6',
 'col_7',
 'col_8',
 'col_9',
 'col_10']

In [3]:
arr = np.random.randint(-10, 11, size=(10, 10))

In [36]:
df = pd.DataFrame({col_names[i]: arr[:,i] for i in range(10)})
df

col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  col_10
0      7    -10      5     -9     -2      4     -1      6     -8       0
1     -5    -10      9     -9      2      8     -3     -5     -3       4
2      5      7      0     -3     -3      5      7    -10     -8      -9
3      4     -5      8      0      8     -9     -2     -2      1      -7
4     -6     -8     -1     -7      3      7     -4      8     -7       4
5    -10      2      8     -2      3      1     10      3     -6      -8
6      6      2      8      9      1      6      0      0     -1      -9
7      8      3      6      1     10      3     10      4     10       0
8     -3      1     -5     -3    -10     -3    -10      9      2      -5
9      9     -6      5     -7    -10     -5     -4      9    -10      -8

# Task 2

В колонках col_1, col_4, col_6 в трех рандомных строках значения сделайте пустыми (NaN). Постарайтесь этот процесс автоматизировать)

In [37]:
col = ['col_1', 'col_4', 'col_6']

In [39]:
# Если имелось ввиду, чтобы одни и те же рандомные строки в этих колонках, то вот:
m, n = df.shape
rows = np.random.randint(0, m, size=3)
rows

array([6, 9, 5])

In [40]:
df1 = df.copy()
df1.loc[rows, col] = np.nan
df1

col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  col_10
0    7.0    -10      5   -9.0     -2    4.0     -1      6     -8       0
1   -5.0    -10      9   -9.0      2    8.0     -3     -5     -3       4
2    5.0      7      0   -3.0     -3    5.0      7    -10     -8      -9
3    4.0     -5      8    0.0      8   -9.0     -2     -2      1      -7
4   -6.0     -8     -1   -7.0      3    7.0     -4      8     -7       4
5    NaN      2      8    NaN      3    NaN     10      3     -6      -8
6    NaN      2      8    NaN      1    NaN      0      0     -1      -9
7    8.0      3      6    1.0     10    3.0     10      4     10       0
8   -3.0      1     -5   -3.0    -10   -3.0    -10      9      2      -5
9    NaN     -6      5    NaN    -10    NaN     -4      9    -10      -8

In [42]:
# Если же имелось ввиду, чтобы рандомные три строки были отдельно для каждой колонки, то вот:
rows = np.random.randint(0, m, size=(3, len(col)))
rows

array([[8, 9, 4],
       [4, 7, 2],
       [5, 8, 9]])

In [45]:
for i in range(len(col)):
    df.loc[rows[i], col[i]] = np.nan
df

col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  col_10
0    7.0    -10      5   -9.0     -2    4.0     -1      6     -8       0
1   -5.0    -10      9   -9.0      2    8.0     -3     -5     -3       4
2    5.0      7      0    NaN     -3    5.0      7    -10     -8      -9
3    4.0     -5      8    0.0      8   -9.0     -2     -2      1      -7
4    NaN     -8     -1    NaN      3    7.0     -4      8     -7       4
5  -10.0      2      8   -2.0      3    NaN     10      3     -6      -8
6    6.0      2      8    9.0      1    6.0      0      0     -1      -9
7    8.0      3      6    NaN     10    3.0     10      4     10       0
8    NaN      1     -5   -3.0    -10    NaN    -10      9      2      -5
9    NaN     -6      5   -7.0    -10    NaN     -4      9    -10      -8

# Task 3

Отберите из датасета 4 рандомных строки и добавте в конец фрейма. (Синтезируем дупликаты.) Обновите индексы. Чтобы в сгенеренном массиве с индексами строк не было повторов, используйте следущую нампай функцию:



```
np.random.choice(10, 4, replace=False)
```

Пристыковать полученные строки в конец датафрейма можно с помощью функции concat:



```
pd.concat([df_1, df_2], axis=0)
```





In [46]:
df = pd.concat([df, df.loc[np.random.choice(10, 4, replace=False)]])
df

col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  col_10
0    7.0    -10      5   -9.0     -2    4.0     -1      6     -8       0
1   -5.0    -10      9   -9.0      2    8.0     -3     -5     -3       4
2    5.0      7      0    NaN     -3    5.0      7    -10     -8      -9
3    4.0     -5      8    0.0      8   -9.0     -2     -2      1      -7
4    NaN     -8     -1    NaN      3    7.0     -4      8     -7       4
5  -10.0      2      8   -2.0      3    NaN     10      3     -6      -8
6    6.0      2      8    9.0      1    6.0      0      0     -1      -9
7    8.0      3      6    NaN     10    3.0     10      4     10       0
8    NaN      1     -5   -3.0    -10    NaN    -10      9      2      -5
9    NaN     -6      5   -7.0    -10    NaN     -4      9    -10      -8
2    5.0      7      0    NaN     -3    5.0      7    -10     -8      -9
6    6.0      2      8    9.0      1    6.0      0      0     -1      -9
7    8.0      3      6    NaN     10    3.0     10      4     10       0
0    7.0    -10      5   -9.0     -2    4.0     -1      6     -8       0

In [47]:
df.reset_index(drop=True, inplace=True)
df

col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  col_10
0     7.0    -10      5   -9.0     -2    4.0     -1      6     -8       0
1    -5.0    -10      9   -9.0      2    8.0     -3     -5     -3       4
2     5.0      7      0    NaN     -3    5.0      7    -10     -8      -9
3     4.0     -5      8    0.0      8   -9.0     -2     -2      1      -7
4     NaN     -8     -1    NaN      3    7.0     -4      8     -7       4
5   -10.0      2      8   -2.0      3    NaN     10      3     -6      -8
6     6.0      2      8    9.0      1    6.0      0      0     -1      -9
7     8.0      3      6    NaN     10    3.0     10      4     10       0
8     NaN      1     -5   -3.0    -10    NaN    -10      9      2      -5
9     NaN     -6      5   -7.0    -10    NaN     -4      9    -10      -8
10    5.0      7      0    NaN     -3    5.0      7    -10     -8      -9
11    6.0      2      8    9.0      1    6.0      0      0     -1      -9
12    8.0      3      6    NaN     10    3.0     10      4     10       0
13    7.0    -10      5   -9.0     -2    4.0     -1      6     -8       0

# Task 4

Получите нампай массив в котором будут степени заполненности по всем строкам.

In [48]:
count_numbers_in_rows = np.array(df.apply(lambda x: n - x.isna().sum(), axis=1))
count_numbers_in_rows

array([10, 10,  9, 10,  8,  9, 10,  9,  8,  8,  9, 10,  9, 10],
      dtype=int64)

# Task 5

Удалите те строки, где количество пропусков от двух. Если один пропуск, то удаление не требуется.

In [55]:
df.drop(df[df.apply(lambda x: x.isna().sum(), axis=1) >= 2].index, inplace=True)
df

col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  col_10
0     7.0    -10      5   -9.0     -2    4.0     -1      6     -8       0
1    -5.0    -10      9   -9.0      2    8.0     -3     -5     -3       4
2     5.0      7      0    NaN     -3    5.0      7    -10     -8      -9
3     4.0     -5      8    0.0      8   -9.0     -2     -2      1      -7
5   -10.0      2      8   -2.0      3    NaN     10      3     -6      -8
6     6.0      2      8    9.0      1    6.0      0      0     -1      -9
7     8.0      3      6    NaN     10    3.0     10      4     10       0
10    5.0      7      0    NaN     -3    5.0      7    -10     -8      -9
11    6.0      2      8    9.0      1    6.0      0      0     -1      -9
12    8.0      3      6    NaN     10    3.0     10      4     10       0
13    7.0    -10      5   -9.0     -2    4.0     -1      6     -8       0

# Task 6

Заполните все пропуски средними по соответствующим колонкам.

In [66]:
df.fillna(df.mean(axis=0), inplace=True)

In [67]:
df

col_1  col_2  col_3     col_4  col_5  col_6  col_7  col_8  col_9  col_10
0     7.0    -10      5 -9.000000     -2    4.0     -1      6     -8       0
1    -5.0    -10      9 -9.000000      2    8.0     -3     -5     -3       4
2     5.0      7      0 -1.571429     -3    5.0      7    -10     -8      -9
3     4.0     -5      8  0.000000      8   -9.0     -2     -2      1      -7
5   -10.0      2      8 -2.000000      3    3.5     10      3     -6      -8
6     6.0      2      8  9.000000      1    6.0      0      0     -1      -9
7     8.0      3      6 -1.571429     10    3.0     10      4     10       0
10    5.0      7      0 -1.571429     -3    5.0      7    -10     -8      -9
11    6.0      2      8  9.000000      1    6.0      0      0     -1      -9
12    8.0      3      6 -1.571429     10    3.0     10      4     10       0
13    7.0    -10      5 -9.000000     -2    4.0     -1      6     -8       0

# Task 7

Переименуйте первую колонку в 'user_id' и все элементы приведите к виду 'ID_15'.. Дробных значений чисел быть не должно.

In [74]:
df.index.name = 'user_id'
df

col_1  col_2  col_3     col_4  col_5  col_6  col_7  col_8  col_9  \
user_id                                                                     
0          7.0    -10      5 -9.000000     -2    4.0     -1      6     -8   
1         -5.0    -10      9 -9.000000      2    8.0     -3     -5     -3   
2          5.0      7      0 -1.571429     -3    5.0      7    -10     -8   
3          4.0     -5      8  0.000000      8   -9.0     -2     -2      1   
5        -10.0      2      8 -2.000000      3    3.5     10      3     -6   
6          6.0      2      8  9.000000      1    6.0      0      0     -1   
7          8.0      3      6 -1.571429     10    3.0     10      4     10   
10         5.0      7      0 -1.571429     -3    5.0      7    -10     -8   
11         6.0      2      8  9.000000      1    6.0      0      0     -1   
12         8.0      3      6 -1.571429     10    3.0     10      4     10   
13         7.0    -10      5 -9.000000     -2    4.0     -1      6     -8   

         col_10  
user_id          
0             0  
1             4  
2            -9  
3            -7  
5            -8  
6            -9  
7             0  
10           -9  
11           -9  
12            0  
13            0

In [84]:
df.index = [f'id_{i}' for i in df.index]
df

col_1  col_2  col_3     col_4  col_5  col_6  col_7  col_8  col_9  \
id_0     7.0    -10      5 -9.000000     -2    4.0     -1      6     -8   
id_1    -5.0    -10      9 -9.000000      2    8.0     -3     -5     -3   
id_2     5.0      7      0 -1.571429     -3    5.0      7    -10     -8   
id_3     4.0     -5      8  0.000000      8   -9.0     -2     -2      1   
id_5   -10.0      2      8 -2.000000      3    3.5     10      3     -6   
id_6     6.0      2      8  9.000000      1    6.0      0      0     -1   
id_7     8.0      3      6 -1.571429     10    3.0     10      4     10   
id_10    5.0      7      0 -1.571429     -3    5.0      7    -10     -8   
id_11    6.0      2      8  9.000000      1    6.0      0      0     -1   
id_12    8.0      3      6 -1.571429     10    3.0     10      4     10   
id_13    7.0    -10      5 -9.000000     -2    4.0     -1      6     -8   

       col_10  
id_0        0  
id_1        4  
id_2       -9  
id_3       -7  
id_5       -8  
id_6       -9  
id_7        0  
id_10      -9  
id_11      -9  
id_12       0  
id_13       0

# Task 8

Удалите повторы по строкам. Приведите индексы в порядок при необходимости.

In [85]:
df_unique = df.drop_duplicates()
df_unique

col_1  col_2  col_3     col_4  col_5  col_6  col_7  col_8  col_9  col_10
id_0    7.0    -10      5 -9.000000     -2    4.0     -1      6     -8       0
id_1   -5.0    -10      9 -9.000000      2    8.0     -3     -5     -3       4
id_2    5.0      7      0 -1.571429     -3    5.0      7    -10     -8      -9
id_3    4.0     -5      8  0.000000      8   -9.0     -2     -2      1      -7
id_5  -10.0      2      8 -2.000000      3    3.5     10      3     -6      -8
id_6    6.0      2      8  9.000000      1    6.0      0      0     -1      -9
id_7    8.0      3      6 -1.571429     10    3.0     10      4     10       0